### ISSUE TITLE
Error message not found! Err code: 75

### ISSUE THREAD

**Issue by helloyw** [dirkjanm/PKINITtools#10]
i need help

```
proxychains4 python3 gettgtpkinit.py test.com/'DC1$' -pfx-base64 `cat DC01.pfx.b64` -pfx-pass "admin"  -dc-ip 172.16.12.8 DC01.ccache
```
```[proxychains] config file found: /etc/proxychains4.conf
[proxychains] preloading /usr/lib/x86_64-linux-gnu/libproxychains.so.4
[proxychains] DLL init: proxychains-ng 4.16
2024-01-04 11:23:56,834 minikerberos INFO     Loading certificate and key from file
INFO:minikerberos:Loading certificate and key from file
2024-01-04 11:23:56,853 minikerberos INFO     Requesting TGT
INFO:minikerberos:Requesting TGT
Traceback (most recent call last):
  File "/home/kali/PKINITtools-master/gettgtpkinit.py", line 349, in <module>
    main()
  File "/home/kali/PKINITtools-master/gettgtpkinit.py", line 345, in main
    amain(args)
  File "/home/kali/PKINITtools-master/gettgtpkinit.py", line 315, in amain
    res = sock.sendrecv(req)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/minikerberos/network/clientsocket.py", line 85, in sendrecv
    raise KerberosError(krb_message)
minikerberos.protocol.errors.KerberosError:  Error Name: KDC_ERR_CLIENT_NAME_MISMATCH Detail: "Error message not found! Err code: 75" 
                                                   

```

**Comment by dirkjanm** [comment]
The actual error here is the `KDC_ERR_CLIENT_NAME_MISMATCH`. Could be related to this: https://twitter.com/Tw1sm/status/1501213260925784065
I've also seen this show up in some other cases.

**Comment by helloyw** [comment]
> The actual error here is the `KDC_ERR_CLIENT_NAME_MISMATCH`. Could be related to this: https://twitter.com/Tw1sm/status/1501213260925784065 I've also seen this show up in some other cases.

Thank you for your reply, my friend
